os: linux
language: php

branches:
  only:
    - master
    - trunk
    - develop
    - /^release\/*/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^feature\/*/
    # Also build tags like 1.1.1 or 1.1 for deployment.
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - $HOME/.composer/cache

php:
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'

env:
  - PHPUNIT=1

jobs:
  fast_finish: true
  include:
    - php: '5.6'
      env: LINT=1 PHPUNIT=1
    - php: '7.4'
      env: PHPUNIT=1
    - php: '8.0'
      env: LINT=1 PHPUNIT=1
    - stage: 🚀 deployment
      name: "Deploy to Yoast-dist"
      php: 7.2
      install:
        - yarn global add grunt-cli
        - yarn install
      before_script: skip
      script:
        - |
          if [[ ! -z "$TRAVIS_TAG" ]]; then
            grunt set-version -new-version=$TRAVIS_TAG
            grunt update-version
          fi
        - grunt artifact
      if: ( tag IS present OR branch =~ /^feature\// OR branch =~ /^release\// OR branch =~ /^hotfix\// OR branch = trunk OR branch = develop ) AND type != pull_request
      before_install:
        - nvm install lts/*
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
        - openssl aes-256-cbc -K $encrypted_d1beccaa5494_key -iv $encrypted_d1beccaa5494_iv -in config/travis/deploy_keys/id_rsa_yoast_dist.enc -out config/travis/deploy_keys/id_rsa_yoast_dist -d
        - chmod 600 config/travis/deploy_keys/id_rsa_yoast_dist
        - eval $(ssh-agent -s)
        - ssh-add config/travis/deploy_keys/id_rsa_yoast_dist

      # If the commit was tagged, create an artifact and push it to the distribution github
      deploy:
        skip_cleanup: true
        provider: script
        script: bash config/travis/deploy_to_dist.sh ${TRAVIS_TAG:-$TRAVIS_BRANCH} duplicate-post
        on:
          repo: $TRAVIS_REPO_SLUG
          all_branches: true

before_install:
  - if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi
  - travis_retry composer install

before_script:
- export -f travis_fold
- export -f travis_time_start
- export -f travis_time_finish

script:
  - if [[ "$LINT" == "1" ]]; then composer lint; fi
  # PHP Unit Tests
  - |
    if [[ "$PHPUNIT" == "1" ]]; then
      travis_fold start "PHP.tests" && travis_time_start
      composer test
      travis_time_finish && travis_fold end "PHP.tests"
    fi
